version: "3"
services:
  lab:
    image: marcpartensky/tsi-ml
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/root/tsi-ml

  training:
    image: marcpartensky/tsi-ml-training
    build: .
    volumes:
      - ./:/root/tsi-ml
    entrypoint: >
      python ./variational_autoencoder.py
